name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types:
      - published
jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Test with Docker
        run: go test -v ./...

      - name: Test
        run: go test -cover -coverprofile=coverage.txt ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt # Make sure to use the same file name you chose for the "-coverprofile" in the "Test" step
  code_coverage:
      name: "Code coverage report"
      if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
      runs-on: ubuntu-latest
      needs: unit_tests # Depends on the artifact uploaded by the "unit_tests" job
      permissions:
        contents: read  # to download code coverage results from unit_tests job
        pull-requests: write # write permission needed to comment on PR
      steps:
        - uses: fgrosse/go-coverage-report@v1.0.2 # Consider using a Git revision for maximum security
          with:
            coverage-artifact-name: "code-coverage" # can be omitted if you used this default value
            coverage-file-name: "coverage.txt" # can be omitted if you used this default value
  DockerHub:
      uses: mimiro-io/.github/.github/workflows/dockerhub.yaml@main
      with:
        name: "mimiro/s3-datalayer"
      secrets:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}